Homework1 fix
made-ml-in-prod-2022/FainaAlimbaeva pull request #1
Opened 2022-05-16 09:28 UTC by FainaAlimbaeva

Самооценка:

0. В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание того, что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код (1 балл)
Постаралась описать в Readme (1)
1. В пулл-реквесте проведена самооценка, распишите по каждому пункту выполнен ли критерий или нет и на сколько баллов(частично или полностью) (1 балл)
Выполнена самооценка (2)
2. Выполнено EDA, закоммитьте ноутбук в папку с ноутбуками (1 балл) Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы)
Выполнено EDA (3)
3. Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкцию по запуску (3 балла)
Выполнено (6)
4. Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme (3 балла)
Выполнено (9)
5. Проект имеет модульную структуру (2 балла)
Выполнено (11)
6. Использованы логгеры (2 балла)
Выполнено (13)
7. Написаны тесты на отдельные модули и на прогон обучения и predict (3 балла)
Выполнено (15)
8. Для тестов генерируются синтетические данные, приближенные к реальным (2 балла)
можно посмотреть на библиотеки https://faker.readthedocs.io/, https://feature-forge.readthedocs.io/en/latest/
можно просто руками посоздавать данных, собственноручно написанными функциями.
Выполнено (17)
9. Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла)
Выполнено  (20)
10. Используются датаклассы для сущностей из конфига, а не голые dict (2 балла)
Выполнено (22)
11. Напишите кастомный трансформер и протестируйте его (3 балла) https://towardsdatascience.com/pipelines-custom-transformers-in-scikit-learn-the-step-by-step-guide-with-python-code-4a7d9b068156
Выполнено (25)
12. В проекте зафиксированы все зависимости (1 балл)
Выполнено (26)
13. Настроен CI для прогона тестов, линтера на основе github actions (3 балла). Пример с пары: https://github.com/demo-ml-cicd/ml-python-package
Выполнено (29)

2022-05-28 21:22 UTC, nickdndev requested changes
1. Добавить в git ignore .idea , кеш питона 
2. не нашел кастомного трансформера 
3. сделать проверку в тестах параметры моделей , а не просто сравнить isinstance 
4. необходимо починить тесты т.к. это самое главное чтобы ci/cd был зеленым , когда красный , то нельзя мерджить в мастер

2022-05-28 21:22 UTC, nickdndev commented on ml_project/tests/test_train_model.py
> +    model = train(transformed_dataset, target, training_params)
validate model after train ( check delta +-5%)

2022-06-14 07:06 UTC, FainaAlimbaeva commented on ml_project/tests/test_train_model.py
> +    model = train(transformed_dataset, target, training_params)
Все вроде получилось.

2022-06-18 18:58 UTC, nickdndev commented
score:26

2022-06-18 18:58 UTC, merged