Homework2
made-ml-in-prod-2022/FainaAlimbaeva pull request #2
Opened 2022-05-30 20:58 UTC by FainaAlimbaeva

Реализованы технологии FastAPI и Docker.

Самооценка:

1. Оберните inference вашей модели в rest сервис на FastAPI, должен быть endpoint /predict (3)

2. Напишите endpoint /health, должен возращать 200, если ваша модель готова к работе (1)

3. Напишите unit тест для /predict (3)

4. Напишите скрипт, который будет делать запросы к вашему сервису (2)

5. Напишите dockerfile, соберите на его основе образ и запустите локально контейнер. Внутри контейнера должен запускаться сервис, написанный в предущем пункте, напишите в readme корректную команду сборки (4/4)

6. Опубликуйте образ, используя docker push (2)

7. Напишите в readme корректные команды docker pull/run, которые должны привести к тому, что локально поднимется на inference ваша модель (1)

8. Проведите самооценку (1)

Итого: 17 баллов

2022-06-23 20:57 UTC, SVizor42 commented on online_inference/app.py
> +from typing import List, Optional
`Optional` не используется

2022-06-23 20:58 UTC, SVizor42 commented on online_inference/app.py
> +def load_object(path: str):
Нужно добавить возвращаемый тип

2022-06-23 21:04 UTC, SVizor42 commented on online_inference/README.md
> +python online_inference/make_request.py
Т.к. путь в данным зафиксирован в скрипте, нужно использовать команду `python make_request.py`

2022-06-24 14:53 UTC, SVizor42 commented on online_inference/test_app.py
> +        features = ["age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal"]
Для этого можно использовать фикстуры

2022-06-24 14:56 UTC, SVizor42 requested changes
В целом, все хорошо.

1. Добавь пару тестов на некорректные входные данные при обращении к /predict, чтобы сервис возвращал код 4хх.
2. Вижу, что есть оптимизации докер образа. Добавь описание в `README` и можно будет получить доп баллы за этот пункт.

2022-07-01 14:05 UTC, FainaAlimbaeva commented on online_inference/app.py
> +from typing import List, Optional
+

2022-07-01 14:05 UTC, FainaAlimbaeva commented on online_inference/app.py
> +def load_object(path: str):
Добавила  "-> Union[RandomForestClassifier, ColumnTransformer]"

2022-07-01 14:05 UTC, FainaAlimbaeva commented on online_inference/README.md
> +python online_inference/make_request.py
+

2022-07-01 14:05 UTC, FainaAlimbaeva commented on online_inference/test_app.py
> +        features = ["age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal"]
добавила

2022-07-01 14:34 UTC, SVizor42 approved these changes
Все хорошо. Можно сливать ветку.

**Сумма: 19 баллов**

2022-07-01 15:38 UTC, merged